INCDIR="../../include"
CC = gcc -g -Wall -I$(INCDIR)
all:testSymboleList 
	cp symboleList.h ../../include
	cp symboleList.o ../../lib
	cp testSymboleList ../../bin
testSymboleList:testSymboleList.o symboleList.o