INCDIR="../../include"
CC = gcc -g -Wall -I$(INCDIR)
all:testSymboleStack
	cp symboleStack.h ../../include
	cp symboleStack.o ../../lib
	cp testSymboleStack ../../bin
testSymboleStack:testSymboleStack.o symboleStack.o